App Broker 2.0.x
spring-cloud/spring-cloud-app-broker pull request #670
Opened 2022-11-29 10:39 UTC by spikymonkey

App Broker 2.0.x

Major dependencies updates:
* Spring Boot 3
* Spring Framework 6
* Spring Cloud Open Service Broker 4.0.0-SNAPSHOT
* Java 17
* Gradle 7.6

Dockerfile:
* Update to Ubuntu Jammy
* Bump to OpenJDK 17
* Remove usage of deprecated `apt-key` tool
* Bump all other tools to latest versions (bosh, bbl, credhub etc.)

ATs:
* Pass required java buildpack env var to use Java 17 on CF
* Update `cf login` invocation to work with cf-cli v8

Small improvements:
* Reliable datetime comparison in `InMemoryServiceInstanceStateRepositoryTest`
* Update `.editorconfig` to match existing style
* Add `.sdkmanrc`

2022-12-05 13:21 UTC, spikymonkey commented
This needs spring-cloud/spring-cloud-open-service-broker#367 to be merged before tests will pass.

2022-12-06 16:11 UTC, royclarkson requested changes
GitHub Actions matrix needs modification, otherwise LGTM!

2022-12-07 18:25 UTC, royclarkson requested changes
Looks good, but have one question.

2022-12-07 18:25 UTC, royclarkson commented on .github/workflows/java-8-baseline.yml
> +        java: [ '8', '11' ]
We should run these on 17 as well

2022-12-07 18:28 UTC, spikymonkey commented on .github/workflows/java-8-baseline.yml
> +        java: [ '8', '11' ]
Done

2022-12-07 18:29 UTC, royclarkson approved these changes
Thanks!

2022-12-08 09:20 UTC, merged